 

```{r}
setwd("C:/Users/SAMET/Desktop/Analytics/BDA 503 Data Analytics Essentials/Project") #Samet

#setwd('C:/Users/Sancak/Documents/R') #Selen

BCD <- read.csv('Baltimore_Crime_Data.csv', header = T,  sep=",")

BCD <- read.csv("/Users/Tunay/R/Baltimore.csv")

head(BCD)
```

```{r}
str(BCD)
```

```{r}
library("data.table")
library("ggplot2")
library("dplyr")

BCD$CrimeDate<-as.Date(BCD$CrimeDate,format="%m/%d/%Y")
BCD$CrimeTimehOUR<- as.integer(substr(BCD$CrimeTime,0,2))
BCD$Year <- as.numeric (format(BCD$CrimeDate,"%Y"))
BCD$Month=as.numeric (format(BCD$CrimeDate,"%m"))
BCD$Day=as.numeric (format(BCD$CrimeDate,"%d"))
unique(BCD$Inside.Outside)
BCD$Inside.Outside[BCD$Inside.Outside=="O"] <- "Outside"
BCD$Inside.Outside[BCD$Inside.Outside=="I"] <- "Inside"
head(BCD)
unique(BCD$Description)
BCD$CrimeGroup[like(BCD$Description,"ROBBERY")] <- "ROBBERY"
BCD$CrimeGroup[like(BCD$Description,"ASSAULT")] <- "ASSAULT"
BCD$CrimeGroup[like(BCD$Description,"LARCENY")] <- "LARCENY"
BCD$CrimeGroup[like(BCD$Description,"ARSON")] <- "ARSON"
BCD$CrimeGroup[like(BCD$Description,"RAPE")] <- "RAPE"
BCD$CrimeGroup[like(BCD$Description,"SHOOTING")] <- "SHOOTING"
BCD$CrimeGroup[like(BCD$Description,"AUTO THEFT")] <- "AUTO THEFT"
BCD$CrimeGroup[like(BCD$Description,"HOMICIDE")] <- "HOMICIDE"
BCD$CrimeGroup[like(BCD$Description,"BURGLARY")] <- "BURGLARY"
BCD$CrimeScore[like(BCD$Description,"ROBBERY - RESIDENCE")] <- 5 
BCD$CrimeScore[like(BCD$Description,"AUTO THEFT")] <-4
BCD$CrimeScore[like(BCD$Description,"SHOOTING")] <-8
BCD$CrimeScore[like(BCD$Description,"AGG. ASSAULT")] <-6
BCD$CrimeScore[like(BCD$Description,"COMMON ASSAULT")] <-4
BCD$CrimeScore[like(BCD$Description,"BURGLARY")] <-10
BCD$CrimeScore[like(BCD$Description,"HOMICIDE")] <-10
BCD$CrimeScore[like(BCD$Description,"ROBBERY - STREET")] <-4
BCD$CrimeScore[like(BCD$Description,"ROBBERY - COMMERCIAL")] <-5
BCD$CrimeScore[like(BCD$Description,"LARCENY")] <-2
BCD$CrimeScore[like(BCD$Description,"LARCENY FROM AUTO")] <-1
BCD$CrimeScore[like(BCD$Description,"ARSON")] <-6
BCD$CrimeScore[like(BCD$Description,"ROBBERY - CARJACKING")] <-3
BCD$CrimeScore[like(BCD$Description,"ASSAULT BY THREAT")] <-1
BCD$CrimeScore[like(BCD$Description,"RAPE")] <-7

BCD$CrimeScore <- as.factor(BCD$CrimeeScore)
BCD$CrimeTimeLine <- cut(BCD$CrimeTimehOUR, breaks=c(0,6,12,18,24), right=TRUE)
unique(BCD$CrimeTimeLine)
ggplot(BCD,aes(x=BCD$CrimeTimeLine)) + geom_bar(stat="count") 

unique(BCD$CrimeGroup)
unique(BCD$CrimeCode)
unique(BCD$Weapon)
subset(BCD,BCD$Weapon=='')
```

```{r Frequency of Incidents by Disctrict}
str(BCD$District) #datatype is factor

BCD$District[BCD$District == ""] <- NA
BCD$District <- as.factor(BCD$District)

BCD$Neighborhood[BCD$Neighborhood == ""] <- NA
BCD$Neighborhood <- as.factor(BCD$Neighborhood)

#reordered District 
BCD$District <- factor(BCD$District,levels = c("CENTER", "WESTERN", "NORTHWESTERN", "NORTHERN", "NORTHEASTERN", "EASTERN","SOUTHEASTERN","SOUTHERN","SOUTHWESTERN"))

unique(BCD$District)
unique(BCD$District) #each row has a single Total.Incident

sort(table(BCD$District), decreasing=T)

ggplot(subset(BCD,!is.na(District)))+
  aes(x=District)+
  geom_bar(stat = "count",color='black',fill="red") + 
  geom_text(stat="count",aes(label=..count..),vjust=-1)+
  labs(title="Frequency of Incidents by Disctrict",x="Districts",y="Number of Incidents")
  
```


```{r Chaning of Incidents in Districts year by year}

unique(BCD$Year)

ggplot(subset(BCD,!is.na(District)))+
  aes(x=Year, fill=District)+
  geom_bar(stat="count")+
  scale_x_continuous(breaks = seq(2012,2017,1))+
  scale_y_continuous(breaks = seq(5000,50000,5000))+
  scale_fill_brewer(type = 'div')+
  labs(title="Frequency of Incidents by Disctrict",x="Districts",y="Number of Incidents")

```

```{r Neighborhood}
unique(BCD$Neighborhood)


BCD.arrange.Neighborhood <- BCD %>%
    group_by(Neighborhood,Year) %>%
    summarise(count=n()) %>%
  arrange(desc(count))

head(BCD.arrange.Neighborhood)

subset(BCD.arrange.Neighborhood,Neighborhood=="Downtown")

#Especillay Downtown has highest number of Incidents

ggplot(subset(BCD.arrange.Neighborhood,Neighborhood=="Downtown" & Year!=2017))+
  aes(x=Year,y=count)+
  geom_line()  +
  geom_point()+
  scale_y_continuous(breaks = seq(1400,2000,100))+
  scale_fill_brewer(type = 'div')+
  labs(title="Number of Incidents in Downtown by Year",x="Year",y="Number of Incidents")



```

# Yiğican Maps

```{r}

library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(sqldf)

states <- map_data("state")


ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)

maryland <- subset(states, region == c("maryland"))

ggplot(data = maryland) + 
  geom_polygon(aes(x = long, y = lat), fill = "palegreen", color = "black") 


maryland2 <- ggplot(data = maryland, mapping = aes(x = long, y = lat, group = group)) + coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")

maryland2

sqldf("select min(Longitude),max(Longitude) from BCD")
sqldf("select min(Latitude),max(Latitude) from BCD")


counties <- map_data("county")

ca_county <- subset(counties, region == "maryland")

maryland3<- maryland2 + theme_nothing() + 
  geom_polygon(data = ca_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA)


# baltimore map

baltimore_map <- maryland3 + 
  coord_fixed(xlim = c(-76.71162, -76.5285),  ylim = c(39.20041, 39.37293) )

baltimore_map

baltimore_map +
  geom_point(data=BCD,aes(x = Longitude, y = Latitude,group=Total.Incidents),colour = 'Red',
             fill="Red",pch=21, size=1, alpha=I(0.005))


baltimore_map +
  geom_point(data=BCD,aes(x = Longitude, y = Latitude,group=Total.Incidents, 
                          colour=CrimeGroup),pch=21, size=1, alpha=I(0.5)) 
  

```




